### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by rudizl** [d-sergienko/ha-tesy#1]
Hi,
can you give me some installation instructions?

10x

**Comment by d-sergienko** [comment]
Hi,

Try to do the following:
1. git clone https://github.com/d-sergienko/ha-tesy.git
2. mv ha-tesy homeassistant/custom_components # move repo directory to custom_components dir of homeassistant
3. ha core restart # restart home assistant
4. Go to 'Settings -> Devices & services -> Add integration' and search for "tesy". An integration should appear in the search results.
5. Select tesy integration from this list and on the next screen enter the IP address of your water heater
6. If setup completed successfully, you should find 1 entity of type 'Thermostat' named like 'Tesy [water-heater-name]'
7. Add this entity to any dashboard and use like any regular thermostat.

Additionally, to use boost mode as a button, you may bind it to the services tesy.boost_on and tesy.boost_off

As this integration was created for my personal only, and now it raises an interest for anyone else, I will reserve some time to create README.

Regards,
Dmitry

**Comment by rudizl** [comment]
Thank you, i'll try as soon as I get home. I've tried that a few days ago, but the directory name was just Tesy, so maybe that was the mistake.

**Comment by d-sergienko** [comment]
Directory name 'tesy' should be fine. In my installation its name is exactly the same.
At what step are you experiensing the difficulty?

**Comment by rudizl** [comment]
4. Go to 'Settings -> Devices & services -> Add integration' and search for "tesy". An integration should appear in the search results.

**Comment by d-sergienko** [comment]
Are there any warnings/errors related to tesy in the log?

Today's evening I will try to setup a new VM with clean HA and reproduce the problem. Will share the findings then.

**Comment by rudizl** [comment]
Hm, now everything works OK. 
![image](https://github.com/user-attachments/assets/e1739fb9-651c-4170-9197-cb7b556fcaaa)
I have to play a bit with boost and current temperature, since I need the second one as a separate entity.
Thanks, maybe it will be useful to create the integration as a custom HACS, or at liest to prepare it for that with all folder structure changes.

**Comment by d-sergienko** [comment]
Thanks for the feedback.
I think the best idea is to merge/adapt my code with existing HACS integration of [Dmitry Krasnoukhov](https://github.com/krasnoukhov/homeassistant-tesy)
I have no plans to continue the development of existing code.

btw, here is the YAML for cards with boost button. Just replace the entity name 'tesy_2000_c8eea614f8f5m' with the name corresponding to your boiler.

```YAML
type: vertical-stack
title: Tesy Water Heater
cards:
  - type: entities
    entities:
      - entity: water_heater.tesy_2000_c8eea614f8f5m
      - type: attribute
        entity: water_heater.tesy_2000_c8eea614f8f5m
        attribute: boost
        name: boost
        icon: mdi:power
  - type: button
    show_name: true
    show_icon: false
    show_state: false
    name: Boost
    tap_action:
      action: call-service
      service: tesy.boost_on
      service_data:
        entity_id: water_heater.tesy_2000_c8eea614f8f5m
      target: {}
    entity: water_heater.tesy_2000_c8eea614f8f5m
    hold_action:
      action: call-service
      service: tesy.boost_off
      service_data:
        entity_id: water_heater.tesy_2000_c8eea614f8f5m
      target: {}
```
